---
title: "ambient_sound"
author: "Rick Gilmore"
date: "`r Sys.time()`"
output: 
  pdf_document:
    fig_caption: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      fig.path = "figs/",
                      fig.align = "center")
library(tidyverse)
csv.dir <- 'csv/'
```

```{r load-sound-data}
snd.fl <- list.files(path = csv.dir, pattern = "^nyu", full.names = TRUE)
snd.fl.df <- lapply(snd.fl, read.csv)
snd.df <- Reduce(function(x, y) merge(x, y, all=TRUE),
                          snd.fl.df)
```

```{r sound-avg-db-plot, fig.cap="Average ambient sound levels in dB across 1 hr by site"}
ggplot(data = snd.df, aes(x=db.avg)) +
  geom_histogram() +
  facet_wrap(facets = c("sub.num")) +
  xlab("db Average") +
  theme_classic() +
  theme(legend.position = "none",
        axis.title = element_text(size = rel(1.5), face ="bold"),
        axis.title.y = element_blank(),
        axis.text = element_text(size = rel(.8)),
        axis.ticks.y = element_blank(),
        axis.text.y = element_blank())
```

```{r sound-peak-db-plot, fig.cap="Peak ambient sound levels in dB across 1 hr by site"}
ggplot(data = snd.df, aes(x=db.peak)) +
  geom_histogram() +
  facet_wrap(facets = c("sub.num")) +
  xlab("dB peak") +
  theme_classic() +
  theme(legend.position = "none",
        axis.title = element_text(size = rel(1.5), face ="bold"),
        axis.title.y = element_blank(),
        axis.text = element_text(size = rel(.8)),
        axis.ticks.y = element_blank(),
        axis.text.y = element_blank())

```

```{r sound-db-combined-plot, fig.cap = "Average and peak ambient sounds levels across 1 hr by site"}
snd.df %>%
  gather(key = snd.measure, value = db, db.avg:db.peak) %>%
  ggplot() +
  aes(x = db, fill = snd.measure) +
  geom_histogram() +
  facet_wrap(facets = c("sub.num")) +
  theme_classic() +
  theme(legend.position = "bottom",
        legend.title = element_blank(),
        legend.text = element_text(size = rel(1.2)),
        axis.title = element_blank(),
        axis.text = element_text(size = rel(.8)),
        axis.ticks.y = element_blank(),
        axis.text.y = element_blank(),
        strip.text = element_text(size = rel(.8)))
```

