---
title: "generate-pilot-summary-data"
author: "Rick Gilmore"
date: "`r Sys.time()`"
output: 
  pdf_document:
    fig_caption: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      fig.path = "figs/",
                      fig.align = "center")
library(tidyverse)
library(choroplethr)
library(choroplethrMaps)
library(databraryapi)

source("R/Cap_all.R")

csv.dir <- 'csv/'

# ggplot
play.palette <- scale_fill_manual(values=c("blue2", "firebrick2", "chartreuse2", "darkorchid2"))

play.theme <-   
  theme_classic() +
  theme(legend.position = "bottom",
        legend.title = element_blank(),
        legend.text = element_text(size = rel(1.2)),
        axis.title = element_text(size = rel(1.5), face ="bold"),
        axis.text.x = element_text(size = rel(1.2)),
        axis.text.y = element_text(size = rel(1.2)),
        axis.line = element_blank(),
        axis.title.y = element_blank())

# Must log in to Databrary
databraryapi::config_db()
databraryapi::login_db()

#
vol.id <- 444 # http://databrary.org/volume/444 is PLAY Project: Pilot Data Collections
slot.id <- 26295 # Materials session with data files
```

```{r summarize-infant-birth}
# cb <- download_asset(asset = 116791, slot = 26295, file.name = "child-birth.csv")

cb <- read_csv("csv/child-birth.csv")
cb$birth_weight_g <- (cb$birth_weight_pounds + cb$birth_weight_ounces/16)*435.92
bw.sum <- round(fivenum(cb$birth_weight_g), 0)
```

```{r locomotor-onset-plot}

locomotion <- read.csv(paste0(csv.dir, "locomotion.csv"))

locomotion %>%
  gather(key = milestone, value = age.mos, hkcrawl_onset_mos, walk_onset_mos) %>%
  mutate(milestone = factor(milestone, labels = c("crawl", "walk"))) %>%
  # arrange(desc(age.mos)) %>%
  ggplot() +
  aes(x = age.mos, y = id) +
  geom_point(aes(shape = milestone, color = milestone)) +
  geom_line(aes(group = id)) +
  xlab("Age (months)") +
  geom_rug(aes(x = age.mos, group = milestone, color = milestone),
           sides = "b") +
  play.theme
```

