---
title: "Make PLAY collection site map"
output:
  github_document: default
params:
  figs.dir: figs/
  databrary.account: default
---

```{r set-up}
knitr::opts_chunk$set(echo = FALSE,
                      fig.path = params$figs.dir,
                      fig.align = "center")

library(tidyverse)
library(ggmap)
library(databraryapi)

PLAY.nichd.vol.id <- 254
PLAY.nichd.session.id <- 26338
PLAY.pis.asset.id <- 117087
PLAY.collection.sites.asset.id <- 117088

if (params$databrary.account == "default") {
  stop("Must specify Databrary account as parameter in file header or in call to rmarkdown::render().")
}
if (!login_db(params$databrary.account)) {
  stop("Error logging in to Databrary. Try config_passwd().")
}
```

```{r PLAY_collection_site_map, include=FALSE, fig.cap="Map of planned PLAY data collection sites."}
# Download data from Databrary
site.data <- read_csv_data_as_df(PLAY.nichd.session.id, PLAY.collection.sites.asset.id, vb = TRUE)

if (!(is.null(site.data))) {
  play.map <- ggmap::get_map(location='united states', 
                             zoom=4, maptype='terrain', 
                             source='google',
                             color='color',
                             force=FALSE)
  if (!(is.null(play.map))) {
    play.collection.map <- ggmap(play.map) +
      ggplot2::geom_point(data = site.data, 
                          aes(x = site.data$lon, 
                              y = site.data$lat, color = "red")) +
      ggplot2::theme(legend.position = "none")
    play.collection.map
    message("Saving collection site map to ", params$figs.dir)
  } else {
    stop("Could not load map.") 
  }
} else {
  stop("Error in reading site data file.")
}
```
